### ISSUE TITLE
ValueError: vendor_id is invalid: None

### ISSUE THREAD

**Issue by Tetsujinfr** [tokoroten-lab/joycon-python#15]
Hi

I got the following error when trying to get the left joycon status:

```
tetsfr@tets:/media/tetsfr/SSD/joycon-python$ python3
Python 3.6.9 (default, Apr 18 2020, 01:56:04) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyjoycon import JoyCon, get_L_id
>>> joycon_id = get_L_id()
>>> joycon = JoyCon(*joycon_id)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/media/tetsfr/SSD/joycon-python/pyjoycon/joycon.py", line 25, in __init__
    raise ValueError(f'vendor_id is invalid: {vendor_id!r}')
ValueError: vendor_id is invalid: None
```

Do you have any idea on how I can fix this?

I am on Jetson with Jetpack 4.4. 
The joycon seems to pair ok via bluetooth but then I got the above error message when trying to access the joycon status/properties.
thanks

**Comment by Tetsujinfr** [comment]
Ok so I got the module to work just great, and the bluetooth connection is rock solid, once properly paired the joycon keeps connected for hours and hours to the Jetson .

Now the difficulty I still have is that the connection properly works only if I remove the Joycon device from the list of previously paired bluetooth devices and add it back. That me be Jetson specific, I do not know, but this is a bit annoying since I would like to automate this process as much as possible.
Closing the issue though since the code works well once the connection is properly established.

**Comment by Tetsujinfr** [comment]
this library is a golden nugget. thanks for this great project!

**Comment by gingershaped** [comment]
_How_ did you fix this? I'm having the same issue!

**Comment by Tetsujinfr** [comment]
Sorry but I do not remember. That might have been related to not having the right bluetooth connectivity library installed. Not sure anymore.

**Comment by spl-cdoebert** [comment]
I had this same issue.  Make sure the Joy-Con is paired to your device (hold down the sync button on the Joy-Con to put it into pairing mode first) the same way any other Bluetooth device would be.  Also, "get_R_id" corresponds specifically to a right Joy-Con; if you're using only a left, use "get_L_id" or this error will pop up.
