### ISSUE TITLE
OSError

### ISSUE THREAD

**Issue by danae678** [tokoroten-lab/joycon-python#20]
When I run 
`from pyjoycon import JoyCon, get_R_id`
`joycon_id = get_R_id()`
`joycon = JoyCon(*joycon_id)`
`joycon.get_status() `

I get the following error :

`OSError: joycon connect failed`

but my joy con shows up in HID devices

**Comment by mxp1234** [comment]
so how to solve it ?
i meet the same problem

**Comment by timqian** [comment]
met the same issue today. Disconnect and reconnect joycon works for me
