### ISSUE TITLE
Mouvements ?

### ISSUE THREAD

**Issue by ToinouX360** [tokoroten-lab/joycon-python#31]
hello,
could you tell me if it is possible to capture the movements in the space of the joycons ? (not the direction/rotation)
Thanks

**Comment by pbsds** [comment]
Tracking position in space requires double integration of the acceleration and orientation, which often result in significant accumulated errors. It's possible, and i did once briefly attempt my hand at it, but i believe the joycons don't have the resolution required for it without significant drift.

**Comment by ToinouX360** [comment]
Ok thanks

**Comment by ToinouX360** [comment]
I close the issue
