### ISSUE TITLE
All variations of get_ids return None

### ISSUE THREAD

**Issue by Daniel2193** [tokoroten-lab/joycon-python#6]
`print(device.get_device_ids())
print(device.get_R_ids())
print(device.get_L_ids())
print(device.get_ids("R"))
print(device.get_ids("L"))`

All of these Return `None` instead of the VID/PID

If I just feed it with the VID/PID from the device manager it crashed an the error message is "vendor_id is invalid"

 `joyconR = JoyCon(0x7E05, 0x0720)` --> `vendor_id is invalid` 

My Setup:
-Windows 10 Home x64
-Python 3.7.5 x64
-Both JoyCons Connected via BT and spinning leds
-PIP packages
->cython (0.29.15)
->joycon-python (0.1.2)
->hidapi (0.9.0.post2)

**Comment by tokoroten-lab** [comment]
Thanks for the report. I'll check it out.

**Comment by tokoroten-lab** [comment]
#7 PR has been merged.
Can you check the behavior?

**Comment by h0m35t4r** [comment]
Also on Windows and trying to connect a Joy-Con over bluetooth. Looking at hid.enumerate(0,0) I see that Joy-Cons return 'Wireless Gamepad' under product_string and not 'Joy-Con'

![joy-con bus reported device description](https://user-images.githubusercontent.com/733146/80486898-ce9e6780-8953-11ea-9c9e-060fba33aff1.png)

**Comment by Daniel2193** [comment]
Sorry for the late response. Still same results. I created a seperate project to test this so i can ensure that nothing else is createing problems. Heres the code: [.](https://pastebin.com/YUQdiBEW) I uninstall the pip package and install it with `pip install https://github.com/tokoroten-lab/joycon-python/archive/master.zip` today (28.04.2020)

**Comment by tokoroten-lab** [comment]
Hi! #11 has been merged!
I checked that it works!!

**Comment by soswow** [comment]
Was this released?
